// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDytZ6uBAcWZmLTl2SzXSjPdFZ1pwKfN5E',
    appId: '1:265652761235:web:61555daa69a0b23af25366',
    messagingSenderId: '265652761235',
    projectId: 'hanziilearningapp',
    authDomain: 'hanziilearningapp.firebaseapp.com',
    storageBucket: 'hanziilearningapp.firebasestorage.app',
    measurementId: 'G-MEPYQ0WGVE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLYRi1PLZWPn8ytkG0tn3Ybe3o9IrNHPg',
    appId: '1:265652761235:android:a4c89909e53fca91f25366',
    messagingSenderId: '265652761235',
    projectId: 'hanziilearningapp',
    storageBucket: 'hanziilearningapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDond1bJcRsn_hH2BdRuBJDvd80OqvmJ9g',
    appId: '1:265652761235:ios:fad62ea2e257e48ff25366',
    messagingSenderId: '265652761235',
    projectId: 'hanziilearningapp',
    storageBucket: 'hanziilearningapp.firebasestorage.app',
    iosBundleId: 'com.example.hanziilearnapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDytZ6uBAcWZmLTl2SzXSjPdFZ1pwKfN5E',
    appId: '1:265652761235:web:ef2e49ab0a942520f25366',
    messagingSenderId: '265652761235',
    projectId: 'hanziilearningapp',
    authDomain: 'hanziilearningapp.firebaseapp.com',
    storageBucket: 'hanziilearningapp.firebasestorage.app',
    measurementId: 'G-N5CBWRQ9MT',
  );
}
